name: Build and Deploy to Firebase Hosting (Live)

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-deploy:
    name: Build and Deploy Live
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Flutter web
        run: flutter config --enable-web

      - name: Fetch dependencies
        run: flutter pub get

      - name: Analyze (optional)
        run: flutter analyze
        continue-on-error: true

      - name: Build web (release)
        run: flutter build web --release

      - name: Deploy to Firebase Hosting (Live)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_VAADLY_PROJECT }}
          projectId: vaadly-project
        # No channelId => deploys to live site
